name: GameLobby
version: 1.1.0
author: Himmelt
main: org.soraworld.lobby.GameLobby
depend: [Violet]
website: https://github.com/Himmelt/GameLobby
description: GameLobby Plugin.
permissions:
  lobby.admin:
    default: op
